retrieved/unpackaged/objects/Armor__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Magical_protection__c</fullName>
        <label>Magical protection</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Physical_protection__c</fullName>
        <label>Physical protection</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Helmet</fullName>
                </value>
                <value>
                    <fullName>Chest Armor</fullName>
                </value>
                <value>
                    <fullName>Gloves</fullName>
                </value>
                <value>
                    <fullName>Belt</fullName>
                </value>
                <value>
                    <fullName>Trousers</fullName>
                </value>
                <value>
                    <fullName>Boots</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>11</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Armor</label>
    <nameField>
        <label>Armor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Armor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieved/unpackaged/objects/Consumable__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Effect__c</fullName>
        <label>Effect</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>11</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Consumable</label>
    <nameField>
        <label>Consumable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consumables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieved/unpackaged/objects/Jewellery__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Magical_Protection__c</fullName>
        <label>Magical Protection</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>11</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Jewellery</label>
    <nameField>
        <label>Jewellery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jewellery</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieved/unpackaged/objects/Other_Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>11</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Other Item</label>
    <nameField>
        <label>Other Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Other Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieved/unpackaged/objects/Preset__c.object
<CustomObject>
    <fields>
        <fullName>Armor_Chest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Armor Chest</label>
        <referenceTo>Armor__c</referenceTo>
        <relationshipLabel>Presets (Armor Chest)</relationshipLabel>
        <relationshipName>Armor_Chest_Preset</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Boots__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Boots</label>
        <referenceTo>Armor__c</referenceTo>
        <relationshipLabel>Presets (Boots)</relationshipLabel>
        <relationshipName>Boots_Preset</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gloves__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Gloves</label>
        <referenceTo>Armor__c</referenceTo>
        <relationshipLabel>Presets</relationshipLabel>
        <relationshipName>Gloves_Preset</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Helmet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Helmet</label>
        <referenceTo>Armor__c</referenceTo>
        <relationshipLabel>Presets (Helmet)</relationshipLabel>
        <relationshipName>Helmet_Preset</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ring1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ring 1</label>
        <referenceTo>Jewellery__c</referenceTo>
        <relationshipLabel>Presets (Ring1)</relationshipLabel>
        <relationshipName>Ring1_Preset</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ring2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ring 2</label>
        <referenceTo>Jewellery__c</referenceTo>
        <relationshipLabel>Presets (Ring2)</relationshipLabel>
        <relationshipName>Ring2_Preset</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trousers__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trousers</label>
        <referenceTo>Armor__c</referenceTo>
        <relationshipLabel>Presets (Trousers)</relationshipLabel>
        <relationshipName>Presets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weapon1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Weapon 1</label>
        <referenceTo>Weapon__c</referenceTo>
        <relationshipLabel>Presets (Weapon1)</relationshipLabel>
        <relationshipName>Weapon1_Preset</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weapon2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Weapon 2</label>
        <referenceTo>Weapon__c</referenceTo>
        <relationshipLabel>Presets (Weapon2)</relationshipLabel>
        <relationshipName>Weapon2_Preset</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Preset</label>
    <nameField>
        <displayFormat>Preset{0}</displayFormat>
        <label>Preset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Presets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieved/unpackaged/objects/Weapon__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Electric_Damage__c</fullName>
        <label>Electric Damage</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fire_Damage__c</fullName>
        <label>Fire Damage</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Physical_Damage__c</fullName>
        <label>Physical Damage</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Poison_Damage__c</fullName>
        <label>Poison Damage</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>One-Handed</fullName>
                    <default>true</default>
                    <label>One-Handed</label>
                </value>
                <value>
                    <fullName>Two-Handed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Water_Damage__c</fullName>
        <label>Water Damage</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>11</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Weapon</label>
    <nameField>
        <label>Weapon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weapons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ItemDataService.cls
global with sharing class ItemDataService {
    
    @AuraEnabled(cacheable=true)
    public static Map<String, List<SObject>> getItems(){
        try {
            Map<String, List<SObject>> items = new Map<String, List<SObject>>();

            List<Armor__c> armorList = getArmor();
            List<Weapon__c> weaponList = getWeapons();
            List<Consumable__c> consumableList = getConsumables();
            List<Jewellery__c> jewelryList = getJewellery();
            List<Other_Item__c> otherList = getOtherItems();

            items.put('Armor', armorList);
            items.put('Weapon', weaponList);
            items.put('Consumable', consumableList);
            items.put('Jewellery', jewelryList);
            items.put('Other', otherList);

            return items;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Armor__c> getArmor(){
        return [SELECT 
        Name, Magical_protection__c, 
        Physical_protection__c, Picture__c, 
        Weight__c, Type__c, Description__c 
        FROM Armor__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<Weapon__c> getWeapons(){
        return [SELECT Name, Electric_Damage__c, 
        Fire_Damage__c, Physical_Damage__c,
        Poison_Damage__c,Water_Damage__c,
        Picture__c, Weight__c, Type__c, 
        Description__c 
        FROM Weapon__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<Jewellery__c> getJewellery(){
        return [SELECT 
        Name, Magical_Protection__c, Picture__c, 
        Weight__c, Description__c 
        FROM Jewellery__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<Consumable__c> getConsumables(){
        return [SELECT 
        Name, Effect__c, Picture__c, 
        Weight__c, Description__c 
        FROM Consumable__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<Other_Item__c> getOtherItems(){
        return [SELECT 
        Name, Picture__c, 
        Weight__c, Description__c 
        FROM Other_Item__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<Preset__c> getPresets(){
            return [
                SELECT Id, Name, 
                Armor_Chest__r.Name, Armor_Chest__r.Magical_protection__c, 
                Armor_Chest__r.Physical_protection__c, Armor_Chest__r.Picture__c, 
                Armor_Chest__r.Weight__c, Armor_Chest__r.Type__c, Armor_Chest__r.Description__c ,
                Boots__r.Name, Boots__r.Magical_protection__c, Boots__r.Physical_protection__c, 
                Boots__r.Picture__c, Boots__r.Weight__c, Boots__r.Type__c, Boots__r.Description__c , 
                Gloves__r.Name, Gloves__r.Magical_protection__c, Gloves__r.Physical_protection__c, 
                Gloves__r.Picture__c, Gloves__r.Weight__c, Gloves__r.Type__c, Gloves__r.Description__c,
                Helmet__r.Name, Helmet__r.Magical_protection__c, Helmet__r.Physical_protection__c, 
                Helmet__r.Picture__c, Helmet__r.Weight__c, Helmet__r.Type__c, Helmet__r.Description__c,
                Ring1__r.Name, Ring1__r.Magical_protection__c, Ring1__r.Picture__c, Ring1__r.Weight__c, Ring1__r.Description__c, 
                Ring2__r.Name, Ring2__r.Magical_protection__c, Ring2__r.Picture__c, Ring2__r.Weight__c, Ring2__r.Description__c, 
                Trousers__r.Name, Trousers__r.Magical_protection__c, Trousers__r.Physical_protection__c, 
                Trousers__r.Picture__c, Trousers__r.Weight__c, Trousers__r.Type__c, Trousers__r.Description__c, 
                Weapon1__r.Name, Weapon1__r.Electric_Damage__c, Weapon1__r.Fire_Damage__c, 
                Weapon1__r.Physical_Damage__c, Weapon1__r.Poison_Damage__c, Weapon1__r.Water_Damage__c,
                Weapon1__r.Picture__c, Weapon1__r.Weight__c, Weapon1__r.Type__c, Weapon1__r.Description__c,
                Weapon2__r.Name, Weapon2__r.Electric_Damage__c, Weapon2__r.Fire_Damage__c, 
                Weapon2__r.Physical_Damage__c, Weapon2__r.Poison_Damage__c, Weapon2__r.Water_Damage__c,
                Weapon2__r.Picture__c, Weapon2__r.Weight__c, Weapon2__r.Type__c, Weapon2__r.Description__c
                FROM Preset__c 
                WITH SECURITY_ENFORCED
                LIMIT 2];
    }

}