retrieved/unpackaged/objects/Armor__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Magical_protection__c</fullName>
        <label>Magical protection</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Physical_protection__c</fullName>
        <label>Physical protection</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Helmet</fullName>
                </value>
                <value>
                    <fullName>Chest Armor</fullName>
                </value>
                <value>
                    <fullName>Gloves</fullName>
                </value>
                <value>
                    <fullName>Belt</fullName>
                </value>
                <value>
                    <fullName>Trousers</fullName>
                </value>
                <value>
                    <fullName>Boots</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>11</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Armor</label>
    <nameField>
        <label>Armor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Armor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieved/unpackaged/objects/Consumable__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Effect__c</fullName>
        <label>Effect</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>11</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Consumable</label>
    <nameField>
        <label>Consumable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consumables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieved/unpackaged/objects/Jewellery__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Magical_Protection__c</fullName>
        <label>Magical Protection</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>11</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Jewellery</label>
    <nameField>
        <label>Jewellery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jewellery</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieved/unpackaged/objects/Other_Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>11</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Other Item</label>
    <nameField>
        <label>Other Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Other Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieved/unpackaged/objects/Preset__c.object
<CustomObject>
    <fields>
        <fullName>Helmet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Helmet</label>
        <referenceTo>Armor__c</referenceTo>
        <relationshipLabel>Presets (Helmet)</relationshipLabel>
        <relationshipName>Helmet_Preset</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ring1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ring 1</label>
        <referenceTo>Jewellery__c</referenceTo>
        <relationshipLabel>Presets (Ring1)</relationshipLabel>
        <relationshipName>Ring1_Preset</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weapon1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Weapon 1</label>
        <referenceTo>Weapon__c</referenceTo>
        <relationshipLabel>Presets (Weapon1)</relationshipLabel>
        <relationshipName>Weapon1_Preset</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Preset</label>
    <nameField>
        <displayFormat>Preset{0}</displayFormat>
        <label>Preset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Presets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieved/unpackaged/objects/Weapon__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Electric_Damage__c</fullName>
        <label>Electric Damage</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fire_Damage__c</fullName>
        <label>Fire Damage</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Physical_Damage__c</fullName>
        <label>Physical Damage</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Poison_Damage__c</fullName>
        <label>Poison Damage</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>One-Handed</fullName>
                    <default>true</default>
                    <label>One-Handed</label>
                </value>
                <value>
                    <fullName>Two-Handed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Water_Damage__c</fullName>
        <label>Water Damage</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>11</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Weapon</label>
    <nameField>
        <label>Weapon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weapons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
public with sharing class TestDataFactory {
    public static List<Armor__c> ConstructArmorItems(Integer cnt){
        List<Armor__c> armorItems = new List<Armor__c>();
        List<String> pickListValuesList= new List<String>();
		Schema.DescribeFieldResult fieldResult = Armor__c.Type__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
		}    
        for(Integer i=0; i<cnt; i++){
            armorItems.add(new Armor__c(
                Name='Test Armor ' + i, Physical_Protection__c=cnt, Magical_Protection__c=cnt-1, 
                Picture__c='testarmorurl/pict'+i, Type__c=pickListValuesList.get(Math.mod(i,pickListValuesList.size())),
                Weight__c = cnt, Description__c='Test Description for item ' + i
            ));
        }
        return armorItems;
    }

    public static List<Weapon__c> ConstructWeaponItems(Integer cnt){
        List<Weapon__c> weaponItems = new List<Weapon__c>();
        List<String> pickListValuesList= new List<String>();
		Schema.DescribeFieldResult fieldResult = Weapon__c.Type__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
		}    
        for(Integer i=0; i<cnt; i++){
            weaponItems.add(new Weapon__c(
                Name='Test Weapon ' + i, Physical_Damage__c=cnt, Poison_Damage__c=cnt, Fire_Damage__c=cnt, Water_Damage__c=cnt, Electric_Damage__c=cnt, 
                Picture__c='testweaponurl/pict'+i, Type__c=pickListValuesList.get(Math.mod(i,pickListValuesList.size())),
                Weight__c = cnt, Description__c='Test Description for item ' + i 
            ));
        }
        return weaponItems;
    }

    public static List<Jewellery__c> ConstructJewelleryItems(Integer cnt){
        List<Jewellery__c> jewelleryItems = new List<Jewellery__c>(); 
        for(Integer i=0; i<cnt; i++){
            jewelleryItems.add(new Jewellery__c(
                Name='Test Jewellery ' + i, Magical_Protection__c=cnt,
                Picture__c='testjewurl/pict'+i,
                Weight__c = cnt, Description__c='Test Description for item ' + i
            ));
        }
        return jewelleryItems;
    }

    public static List<Consumable__c> ConstructConsumableItems(Integer cnt){
        List<Consumable__c> consumableItems = new List<Consumable__c>(); 
        for(Integer i=0; i<cnt; i++){
            consumableItems.add(new Consumable__c(
                Name='Test Consumable ' + i, Effect__c='Test effect',
                Picture__c='testconsurl/pict'+i,
                Weight__c = cnt, Description__c='Test Description for item ' + i
            ));
        }
        return consumableItems;
    }

    public static List<Other_Item__c> ConstructOtherItems(Integer cnt){
        List<Other_Item__c> otherItems = new List<Other_Item__c>(); 
        for(Integer i=0; i<cnt; i++){
            otherItems.add(new Other_Item__c(
                Name='Test Other Item ' + i, Picture__c='testotherurl/pict'+i,
                Weight__c = cnt, Description__c='Test Description for item ' + i
            ));
        }
        return otherItems;
    }

    public static Preset__c ConstructPreset(Armor__c helmet, Weapon__c weapon1, Jewellery__c ring1){
        return new Preset__c(Helmet__c=helmet.Id, Weapon1__c = weapon1.Id, Ring1__c=ring1.Id);
    }

    public static void InsertTestData(Integer cnt){
        List<Armor__c> armorItems = ConstructArmorItems(cnt);
        insert armorItems;
        List<Weapon__c> weaponItems = ConstructWeaponItems(cnt);
        insert weaponItems;
        List<Jewellery__c> jewelleryItems = ConstructJewelleryItems(cnt);
        insert jewelleryItems;
        List<Consumable__c> consumableItems = ConstructConsumableItems(cnt);
        insert consumableItems;
        List<Other_Item__c> otherItems = ConstructOtherItems(cnt);
        insert otherItems;
        Preset__c preset = ConstructPreset(armorItems[0], weaponItems[0], jewelleryItems[0]);
        insert preset;
    }
}